[project]
name = "job-posting"
version = "0.1.0"
description = "NLP classifier and NER"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.30.1",
    "kagglehub[pandas-datasets]>=0.3.12",
    "pandas>=2.3.1",
    "path>=17.1.1",
    "pip>=25.2",
]
